### ISSUE TITLE
Logout do passaporte

### ISSUE THREAD

**Issue by joaopslins** [acmh/gymquery#1]
- Ver um meio de colocar a token dentro da sessão do passaporte, pro cara deslogar direito.
- Colocar a token no header dos requests

**Comment by acmh** [comment]
Vou abandonar o login por sessão (no caso utilizando Passport). Utilizaremos apenas autenticação por tokens.

**Comment by acmh** [comment]
Resolvi utilizar apenas usando token por vários motivos:
- Ao utilizar Passport e Tokens deixaria aplicação redudante (apesar de existir sistemas híbridos) e adicionando também mais código boilerplate por causa dos métodos do Passport. O que não seria interessante para aplicação nem para o desenvolvimento.
- Questões de perfomance: Decodificar um token é muito mais rápido do que ficar fazendo consultas a tabelas de sessões.
- Escalabilidade
