### ISSUE TITLE
Mudanças nas rotas de questão e de lista de questões

### ISSUE THREAD

**Issue by joaopslins** [acmh/gymquery#10]
- [ ] Mudar rota de questão para retornar o nome das tabelas e os campos de cada uma. (O cara precisa saber isso pra poder responder a questão)
- [x] Mudar a rota de lista de questões para retornar a data, para a lista ser ordenada por data.

Sim? Não? Talvez? O que acha?

@acmh

**Comment by acmh** [comment]
Sim, concordo em bem lembrado quanto retornar o nome das tabelas. É bom retornar o script de criação e povoamento pra abrir num model separado com highlight. O que tu acha?

**Comment by joaopslins** [comment]
Tecnicamente não precisa saber como foi povoado. Nem o script de criação em si, só as tabelas e as colunas.

Se fizer alguma análise aí do script de criação dá pra tirar o nome das tabelas/colunas já, aí é só mandar e formatar direitinho na página.

Quanto à data, vou esperar essa mudança, só dar check na box quando for implementado.
