### ISSUE TITLE
Rota /usersPaginated

### ISSUE THREAD

**Issue by joaopslins** [acmh/gymquery#18]
Criar rota /usersPaginated.

Igual ao /questionsPaginated mas busca pelo nome

```javascript
		function getUserList(search, page) {
			return $http({
				method: "GET",
				url: "/usersPaginated",
				params: {
					name: search.name,
					page: page
				}
			});
		};
```
Retornar o objeto como "users" em vez de "questions".

**Comment by acmh** [comment]
O commit [2c6040066188ef08bb1873048d1ce06859451db3](https://github.com/acmh/gymquery/commit/2c6040066188ef08bb1873048d1ce06859451db3) resolve essa issue

**Comment by joaopslins** [comment]
Fazer com que pesquise sem ser Case Sensitive no back-end
