### ISSUE TITLE
Views implementadas

### ISSUE THREAD

**Issue by joaopslins** [acmh/gymquery#2]
Update : Essa issue servirá para tomar decisões das implementações iniciais das views, e checar o andamento delas
- [ ] Home
- [x] Login
- [ ] Questões
  - [x] Criar questão
  - [x] Lista de Questões
  - [x] Visualizar uma questão
  - [ ] Editar questão
- [ ] Submissões
- [ ] Usuários
# 

Melhor assim separado mesmo ou numa tela só?
O que vai ter na home?

**Comment by acmh** [comment]
Eu gostei de ser separado. Fica melhor e mais organizado.
- **Home**: Na home poderia ter as abas pra justamente a gente transitar para Questões e Profile por exemplo (profile entenda como mudar senha, nome do usuário, mudar email) e além disso, digamos no "corpo" do home ter um dashboard com um gráfico dizendo a quantidade de questões resolvidas.

**Comment by joaopslins** [comment]
Isso a gente já tem na navbar, no topo da página. No corpo da Home seria melhor algo mais visual então? É isso que queres dizer?

Informações gerais do perfil do cara então. Beleza, saquei, faz sentido. Mas e quando o cara não tiver logado?

**Comment by acmh** [comment]
Isso, algo mais visual mesmo. Quando o cara não tiver logado redireciona pra uma landing page.

**Comment by joaopslins** [comment]
Vou mudar o primeiro post pra ser uma checklist

**Comment by joaopslins** [comment]
View de visualizar questão implementada no commit 7ccadef441dc5a3611a2772907dc9c5bb0378650
