### ISSUE TITLE
Modelagem das submissões no banco

### ISSUE THREAD

**Issue by joaopslins** [acmh/gymquery#3]
Como será?

**Comment by acmh** [comment]
O que eu imaginei foi o seguinte:

_"Cada submissão de um usuário gera um ID, logo assim associaremos um usuário a uma ou várias submissões"_

Tendo isso em mente:
1.  Receberemos o **ID** da submissão e **SOURCE CODE** do usuário, bem como o ID da questão.
2. Verificaremos a existência de código proibido como por exemplo **DROP TABLE** e outras palavras mais no source code do aluno.
3.  Se tudo estiver correto, com o ID da questão, pegaremos o script de povoamento, o script de resposta (aquele criado pelo monitor).
4. Colocaremos numa fila a submissão, imagine um objeto chamado Submissão, onde conterá os seguintes atributos: script de povoamento, script de resposta-monitor, script de resposta-aluno, id da submissão.
5. Quando a Submissão estiver na sua vez de ser corrigida, povoaremos o banco com o script de povoamento, rodamos o script de resposta-monitor, armazenamos sua resposta, a mesma coisa faremos com o script de resposta-aluno. Após isso, caso não haja erro anteriormente, por exemplo erro de sintaxes no script, compararemos as respostas linha a linha.
6. Retornaremos o veredito da submissão.

**Comment by acmh** [comment]
E eu vou desacoplar essa parte da submissão. Vou no caso, fazer outro app chamado Corretor. Onde essa parte que a gente já tá fazendo fica "ouvindo" se o Corretor mandou algo, e a mesma coisa o Corretor, fica ouvindo nossa aplicação. Uma vez que Node.js é baseado em eventos, isso não será um problema.
