### ISSUE TITLE
Criação da rota getQuestionsPaginated

### ISSUE THREAD

**Issue by acmh** [acmh/gymquery#6]
Objetivo:
- [x] Modificar backend para comparar a string de título da questão com substring
# 

Essa rota é referente a listagem de questões de forma paginada. Essa rota espera um número de uma página (começando do valor 1) e assim retorna 10 registros do mesmo (esse valor também pode ser modificado dependendo das nossas necessidades). 

Há também algumas opções de filtros que podem ser enviadas pela URL, por exemplo:
- Busca por autor
- Busca por título
- Busca por Tags

Favor olhar o arquivo question.server.controller.js na função **getQuestionsPaginated** para mais informações e sugestões.

**Comment by joaopslins** [comment]
A view de lista de questões já está implementada (mostrando  os 10 primeiros resultados).

Ainda está pendente a pesquisa e o botão de obter mais resultados.

O resultado da rota também foi alterado (não retorna mais background e agora retorna tags).

**Comment by joaopslins** [comment]
Link para visualizar a questão foi implementado.

**Comment by joaopslins** [comment]
No commit 2113505 a busca na lista de questões e a paginação estão implementadas.
Falta modificar a busca por título da questão para poder buscar substrings, em vez de comparar a string toda.
